### ISSUE TITLE
Discord Notifications

### ISSUE THREAD

**Issue by andranoxi** [moderndx/Modern-Anti-Cheat#1]
Instead of sending webhooks to your server, wouldn't it make more sense to just keep that within the server operator's grasp, and not share it with whatever logging you may have going on that specific server? Along with that, if that service ever goes down, this functionality will be effectively nullified until the file is updated.

You're already http.Post, might as well just send it off to Discord instead of adding the extra steps. While I can understand, it might be a pain to get http.Post to play nice with Discord's layout, it's much safer than sending a URL to an arbitrary URL and having that host post to it rather than your own. 

https://github.com/moderndx/Modern-Anti-Cheat/blob/92d25daff7b3f034d8fe73c2cda0d6714e05f066/modern-anti-cheat/lua/autorun/server/sv_mac.lua#L49

**Comment by moderndx** [comment]
The webserver where its hosted will stay up, its used to create logs to improve the ac like fixing false-positives and whatnot.

When I release 2.0 ill release the php file incase the webserver does go down
