### ISSUE TITLE
Not a server owner, but found a MAC bypass. Does this work?

### ISSUE THREAD

**Issue by RadsammyT** [moderndx/Modern-Anti-Cheat#11]
https://www.unknowncheats.me/forum/garry-s-mod/382544-modern-anti-cheat-bypass.html#post2729326

Found this at UnknownCheats.me, and I wonder if this bypass works.
If there is, is there a patch for it? I am makings this on behalf of a server I play on frequently.

**Comment by Maldevelops** [comment]
Yes, Modern is quite outdated already. For the patch their is no real patch to my knowledge of course.
